## delivery_data

In [1]:
import pandas as pd
import numpy as np

In [11]:
delit = pd.read_csv("gift/delivery_eta_test.csv")
delit.head()

,Order_ID,Distance_km,Prep_Time_min,Riders_Available,Order_Queue,Weather,Rain_mm,Temp_C,Wind_mps,Rush_Hour,DayOfWeek,Time_Slot,Vehicle,Road_Type,Promo,Tip_Level,Delivery_Time_min
0,11702,16.4,14,7,2,Rain,2.8,34.3,2.2,0,2,Dinner,Car,Downtown,1,1,100.5
1,13294,5.3,16,14,4,Clear,0.0,7.0,2.6,1,2,Lunch,Bike,Downtown,0,3,66.3
2,12162,5.4,13,8,6,Rain,1.7,22.6,3.6,1,4,Dinner,Bike,Downtown,0,1,76.3
3,11137,20.0,17,3,1,Rain,4.8,28.0,3.0,1,2,Lunch,Scooter,Suburban,0,1,146.4
4,10988,7.4,16,11,0,Snow,8.1,21.4,2.8,0,0,Dinner,Scooter,Downtown,0,2,79.1

In [13]:
deli = pd.read_csv("gift/delivery_eta_train.csv")
deli.head()

,Order_ID,Distance_km,Prep_Time_min,Riders_Available,Order_Queue,Weather,Rain_mm,Temp_C,Wind_mps,Rush_Hour,DayOfWeek,Time_Slot,Vehicle,Road_Type,Promo,Tip_Level,Delivery_Time_min
0,11502,6.1,15,9,3,Clear,0.0,14.9,1.2,1,1,Dinner,Scooter,Suburban,0,2,59.7
1,12587,7.5,14,15,6,Clear,0.0,14.3,3.0,0,0,Lunch,Scooter,Downtown,1,3,62.9
2,12654,17.6,24,14,4,Rain,4.8,27.0,3.2,0,0,Dinner,Bike,Downtown,0,2,134.7
3,11056,6.8,15,11,5,Clear,0.0,9.2,5.4,0,3,Night,Scooter,Highway,0,0,60.1
4,10706,19.6,16,11,2,Clear,0.0,11.8,2.6,1,2,Dinner,Bike,Downtown,0,1,149.2

In [14]:
## 변수명
# 타깃(예측할 값)
# Delivery_Time_min : 주문 후 고객에게 도착하기까지 총 소요 시간(분)
# 특징(입력 변수) 예시
# Distance_km : 거리(km)
# Prep_Time_min : 음식 준비시간(분)
# Riders_Available : 주변 가용 라이더 수(명)
# Order_Queue : 매장 주문 적체(건)
# Weather : 날씨(맑음/비/눈/안개)
# Rain_mm : 강수량(mm)
# Temp_C : 기온(°C)
# Wind_mps : 풍속(m/s)
# Rush_Hour : 러시아워 여부(0/1)
# DayOfWeek : 요일(0=월 … 6=일)
# Time_Slot : 시간대(Morning/Lunch/Afternoon/Dinner/Night)
# Vehicle : 배달수단(Bike/Scooter/Car)
# Road_Type : 도로환경(Downtown/Suburban/Highway)
# Promo : 프로모션 여부(0/1)
# Tip_Level : 팁 수준(0~3)

In [15]:
deli.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           4000 non-null   int64
 1   Distance_km        4000 non-null   float64
 2   Prep_Time_min      4000 non-null   int64
 3   Riders_Available   4000 non-null   int64
 4   Order_Queue        4000 non-null   int64
 5   Weather            4000 non-null   str
 6   Rain_mm            4000 non-null   float64
 7   Temp_C             4000 non-null   float64
 8   Wind_mps           4000 non-null   float64
 9   Rush_Hour          4000 non-null   int64
 10  DayOfWeek          4000 non-null   int64
 11  Time_Slot          4000 non-null   str
 12  Vehicle            4000 non-null   str
 13  Road_Type          4000 non-null   str
 14  Promo              4000 non-null   int64
 15  Tip_Level          4000 non-null   int64
 16  Delivery_Time_min  4000 non-null   float64
dtypes: float64(5), int64(8), str(4)
memory usage: 531.4 KB

In [16]:
deli_row = deli.copy()

In [17]:
deli.isnull().sum()

Order_ID             0
Distance_km          0
Prep_Time_min        0
Riders_Available     0
Order_Queue          0
Weather              0
Rain_mm              0
Temp_C               0
Wind_mps             0
Rush_Hour            0
DayOfWeek            0
Time_Slot            0
Vehicle              0
Road_Type            0
Promo                0
Tip_Level            0
Delivery_Time_min    0
dtype: int64

In [18]:
deli = deli.drop(['Order_ID'], axis=1)
deli = deli.drop(['Rain_mm'], axis=1)
deli = deli.drop(['Temp_C'], axis=1)
deli = deli.drop(['Wind_mps'], axis=1)

In [19]:
delit = delit.drop(['Order_ID'], axis=1)
delit = delit.drop(['Rain_mm'], axis=1)
delit= delit.drop(['Temp_C'], axis=1)
delit = delit.drop(['Wind_mps'], axis=1)

In [20]:
deli.head()

,Distance_km,Prep_Time_min,Riders_Available,Order_Queue,Weather,Rush_Hour,DayOfWeek,Time_Slot,Vehicle,Road_Type,Promo,Tip_Level,Delivery_Time_min
0,6.1,15,9,3,Clear,1,1,Dinner,Scooter,Suburban,0,2,59.7
1,7.5,14,15,6,Clear,0,0,Lunch,Scooter,Downtown,1,3,62.9
2,17.6,24,14,4,Rain,0,0,Dinner,Bike,Downtown,0,2,134.7
3,6.8,15,11,5,Clear,0,3,Night,Scooter,Highway,0,0,60.1
4,19.6,16,11,2,Clear,1,2,Dinner,Bike,Downtown,0,1,149.2

In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
deli['Weather'] = encoder.fit_transform(deli['Weather'])
deli['Time_Slot'] = encoder.fit_transform(deli['Time_Slot'])
deli['Vehicle'] = encoder.fit_transform(deli['Vehicle'])
deli['Road_Type'] = encoder.fit_transform(deli['Road_Type'])

delit['Weather'] = encoder.fit_transform(delit['Weather'])
delit['Time_Slot'] = encoder.fit_transform(delit['Time_Slot'])
delit['Vehicle'] = encoder.fit_transform(delit['Vehicle'])
delit['Road_Type'] = encoder.fit_transform(delit['Road_Type'])

In [22]:
deli.head()

,Distance_km,Prep_Time_min,Riders_Available,Order_Queue,Weather,Rush_Hour,DayOfWeek,Time_Slot,Vehicle,Road_Type,Promo,Tip_Level,Delivery_Time_min
0,6.1,15,9,3,0,1,1,1,2,2,0,2,59.7
1,7.5,14,15,6,0,0,0,2,2,0,1,3,62.9
2,17.6,24,14,4,2,0,0,1,0,0,0,2,134.7
3,6.8,15,11,5,0,0,3,4,2,1,0,0,60.1
4,19.6,16,11,2,0,1,2,1,0,0,0,1,149.2

In [23]:
delit.head()

,Distance_km,Prep_Time_min,Riders_Available,Order_Queue,Weather,Rush_Hour,DayOfWeek,Time_Slot,Vehicle,Road_Type,Promo,Tip_Level,Delivery_Time_min
0,16.4,14,7,2,2,0,2,1,1,0,1,1,100.5
1,5.3,16,14,4,0,1,2,2,0,0,0,3,66.3
2,5.4,13,8,6,2,1,4,1,0,0,0,1,76.3
3,20.0,17,3,1,2,1,2,2,2,2,0,1,146.4
4,7.4,16,11,0,3,0,0,1,2,0,0,2,79.1

In [24]:
X_train = deli.drop(['Delivery_Time_min'], axis=1)
y_train = deli['Delivery_Time_min']

X_test = delit.drop(['Delivery_Time_min'], axis=1)
y_test = delit['Delivery_Time_min']

In [25]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [26]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=3333)
model.fit(X_train_scaled, y_train)

RandomForestRegressor(random_state=3333)

In [27]:
print("학습데이터점수 :", model.score(X_train_scaled, y_train))
print("테스트데이터점수 :", model.score(X_test_scaled, y_test))

학습데이터점수 : 0.9909914400154838
테스트데이터점수 : 0.9386808080388184

In [28]:
pred = model.predict(X_test_scaled)
pred

array([108.954,  66.674,  71.314, 139.478,  89.361,  66.786,  35.953,
        65.539,  62.98 ,  45.072,  61.371,  53.619,  48.519,  65.3  ,
        53.078,  59.833,  74.213, 106.244,  41.93 ,  68.724,  54.133,
       115.496,  78.084,  78.351,  98.201,  58.451,  49.062,  44.343,
        89.025,  70.783,  71.316, 112.874, 143.483,  72.613,  62.226,
        56.833,  32.635,  51.753,  62.459,  93.369,  98.488,  54.686,
        69.973,  90.497,  56.595, 121.389, 129.121,  48.387,  76.357,
        73.468,  84.229, 104.17 ,  48.561,  44.165,  98.174,  61.404,
        55.629,  56.347, 126.364,  57.054,  45.836,  51.533,  60.816,
        74.359,  73.271,  64.352,  66.102,  37.247,  54.922, 107.564,
        82.936,  64.628,  29.888,  67.404,  29.118,  56.606,  55.261,
        46.697,  75.641,  63.813,  56.203,  54.37 ,  62.735,  80.898,
        66.512,  48.695,  64.211,  57.496,  70.112,  54.493,  62.545,
        67.568,  80.705,  64.16 ,  47.36 ,  39.788,  46.551,  54.31 ,
        99.628,  61.743,  47.273,  62.476, 102.433,  50.827,  48.934,
        48.06 ,  85.836,  60.604,  72.882, 127.819,  48.684,  78.168,
        47.156,  45.247,  78.156,  71.395,  50.843,  44.246,  67.968,
        83.996,  82.805,  87.079,  78.957,  57.973,  79.131,  73.266,
        63.277,  49.266,  44.286,  45.863,  70.839,  88.355,  54.988,
        78.149,  54.025,  63.684,  71.76 ,  61.309,  64.583,  65.103,
        64.545,  60.105, 113.09 ,  99.257,  77.506,  55.073,  74.958,
        49.294,  53.442,  48.275,  62.043,  65.209,  86.577,  75.257,
        41.084,  86.78 ,  53.265, 103.799,  45.304,  74.439,  54.083,
        78.511,  77.438,  99.69 ,  64.928,  41.591,  54.195,  56.458,
        56.267,  72.893,  49.949,  62.914,  72.938, 100.63 ,  64.204,
        50.512,  76.435,  54.39 ,  44.839,  57.895,  82.842,  49.534,
       103.479,  67.   ,  73.578,  44.611,  54.497,  68.025,  58.124,
        55.393,  47.552,  48.353,  73.651,  71.909,  79.469,  49.735,
        83.112,  52.731,  64.508,  67.648,  92.318,  64.128,  52.679,
        68.719,  60.498,  62.386,  47.998,  62.034,  61.145, 124.605,
        76.361,  92.102,  76.159,  65.613,  46.785,  64.493,  49.869,
        46.251,  40.882,  54.576, 104.983,  63.848,  53.034, 105.831,
        46.03 ,  47.043,  45.523,  58.96 ,  81.829,  49.158,  51.599,
        61.802,  71.484,  55.652,  69.413,  63.281,  52.308,  44.506,
        45.335,  62.688,  51.334,  92.081, 100.723,  74.693,  45.141,
        60.477,  59.76 ,  48.222,  78.091,  57.876,  43.62 ,  54.948,
        55.067,  61.221,  81.053,  44.295,  49.08 ,  67.491,  43.066,
        69.366,  66.881,  59.063,  71.948,  95.853,  51.403,  73.986,
        45.806,  45.812,  56.299,  94.313, 137.042,  48.659,  46.043,
        70.145,  50.501,  41.583,  60.91 ,  47.482,  53.44 , 120.497,
        51.336,  78.948,  52.085,  35.356,  51.659, 117.498,  34.502,
        63.755,  44.066, 110.54 ,  38.677,  81.44 , 120.968,  76.333,
        58.748,  45.088,  57.139, 141.887,  57.008,  53.328, 104.837,
        61.124,  58.015,  68.015,  61.577,  49.345,  77.302, 110.769,
        58.228,  35.243,  46.245,  53.143,  63.866,  91.304,  68.478,
        64.384,  82.204,  51.819, 119.04 ,  48.938,  71.742,  57.964,
        60.704,  71.049,  50.972,  60.199,  51.638, 137.369,  70.771,
        51.04 ,  95.028,  67.778,  67.313,  61.698,  56.473,  55.705,
        67.59 ,  37.615,  46.799,  55.432, 101.965,  79.118,  48.559,
        45.04 ,  77.612,  64.407,  83.747,  36.578,  57.902,  30.316,
        44.215,  40.364, 105.916,  45.008,  40.802,  52.564,  81.668,
        53.199,  61.685,  45.674,  57.685,  70.968,  53.907,  77.683,
        66.005,  70.504,  66.632,  83.658,  39.117, 108.523,  68.104,
        35.636,  71.79 ,  64.881,  44.072,  41.321,  99.241,  84.946,
        41.045,  46.715,  80.935,  70.309,  47.118,  67.879,  49.126,
        68.891, 137.716,  64.262,  35.311,  81.192,  51.407, 113.218,
        28.158,  89.754,  84.756,  69.144,  79.905,  64.896,  71.146,
        66.03 ,  69.764,  66.429,  50.263, 101.773,  76.515,  81.713,
        61.584,  53.418, 135.356,  62.27 ,  84.329,  95.341,  51.874,
        95.59 ,  51.061, 107.396, 117.177,  65.528,  61.176,  44.325,
       120.938,  70.085,  34.134,  71.564,  52.438,  72.417,  61.653,
       134.423,  48.292,  77.143,  92.046,  63.299,  47.9  ,  59.361,
        48.346,  59.296,  54.2  ,  40.088,  52.671,  55.027,  49.065,
        54.13 ,  86.501,  42.237,  55.253,  79.31 ,  81.183,  71.746,
        42.279,  41.394,  54.026,  71.668, 103.462,  67.336,  52.139,
        64.495,  81.276,  39.453,  31.094,  38.067,  63.783,  81.337,
        65.113,  73.324,  81.847,  86.992,  64.219,  59.706,  49.654,
        79.989,  57.977,  41.307,  60.225,  64.145,  67.754,  61.121,
        76.509,  81.839,  56.277,  66.847,  67.194,  82.042,  56.076,
        59.255,  49.534,  70.436,  49.584,  81.159,  46.177, 146.662,
        71.264,  60.492,  62.965,  38.575,  57.299,  58.121,  53.428,
        99.872,  95.342,  50.312,  75.228,  74.342,  59.652,  56.561,
        37.955,  34.583,  81.997,  47.54 ,  73.932,  46.19 ,  91.055,
       100.609,  43.694,  90.703, 108.075,  36.762,  50.102, 115.574,
       120.144, 105.577,  63.853,  82.801,  69.872,  44.783,  58.19 ,
        87.938,  89.339, 101.556,  51.645,  41.273,  58.864,  79.158,
        40.631, 125.886, 111.222,  72.398,  42.32 ,  72.141,  63.727,
        49.077,  89.34 ,  81.972,  68.769,  65.779,  45.879,  50.017,
        77.955,  63.757,  44.091,  43.001,  68.063,  68.31 ,  64.094,
        69.822,  46.426,  52.418,  62.313,  96.766,  71.05 ,  53.037,
        64.422,  47.959, 121.31 ,  67.509,  68.56 ,  58.807,  52.073,
        60.927,  79.862,  47.569,  66.527,  72.317, 118.732,  44.818,
        34.415,  63.18 ,  97.082,  51.75 ,  56.061,  58.979,  44.036,
        73.98 ,  70.049,  54.066,  68.417,  88.596,  84.806,  75.531,
        34.53 ,  47.302,  62.736,  50.673,  52.22 ,  71.626,  65.201,
        81.85 ,  35.868,  56.149,  78.225,  91.262,  67.155,  70.843,
        86.935,  50.011,  76.781,  92.829,  53.99 ,  38.182,  46.657,
        64.447,  75.595,  62.978,  73.297,  41.971,  50.623, 109.85 ,
        50.25 ,  52.942,  70.636,  88.143,  55.182,  52.672, 108.505,
        57.317,  43.297,  50.796,  60.53 ,  29.748, 108.092,  63.589,
        49.695,  50.848,  55.713,  62.762,  58.836,  77.293,  45.995,
        37.438,  85.15 ,  42.388,  42.144,  81.62 ,  70.08 ,  53.309,
        62.703,  61.797,  62.035,  52.992,  57.86 ,  54.765,  85.147,
        74.102,  74.472,  71.246, 115.238,  54.96 ,  70.211,  63.638,
        72.849,  61.99 ,  63.939,  65.229,  56.507, 113.664,  59.26 ,
        54.991,  67.35 ,  47.167,  65.928,  61.081,  57.589,  82.984,
        87.604,  48.798,  83.999,  69.332,  51.894,  59.494,  71.847,
        76.534,  61.118,  53.602, 100.329,  68.334,  65.861,  69.682,
        61.809,  57.714,  59.181,  77.376,  82.671,  89.718,  64.524,
        51.581,  64.728,  44.844, 103.607,  50.927,  67.791,  78.557,
        82.157,  81.414,  37.922, 117.664,  59.663,  42.571,  73.548,
        64.7  ,  61.112,  63.709,  36.09 ,  74.269,  46.21 ,  59.768,
        53.053,  60.158,  62.063,  95.706,  55.974,  67.629,  67.362,
        53.68 ,  73.885,  43.506,  39.981,  68.485,  47.397,  55.117,
        55.499,  62.911,  42.032,  62.713, 104.965,  89.785,  58.661,
        55.633,  61.31 ,  64.704,  38.286,  39.748,  88.283,  53.927,
        55.834,  88.072,  38.002,  94.076,  73.901,  76.696,  51.176,
        44.226,  66.542,  51.058,  53.17 ,  62.451, 105.615,  82.09 ,
        59.443,  67.432,  43.051,  55.564,  67.816,  36.143,  58.044,
        80.139,  79.985,  31.806, 103.504,  52.677,  39.848, 120.031,
        92.333,  65.815,  47.467,  66.056,  53.559,  45.64 ,  73.869,
        42.819,  79.105,  46.745,  38.101,  45.964,  65.377,  56.687,
        68.875,  60.663,  84.025,  50.213,  68.379,  64.112,  46.322,
       102.508,  58.464,  52.065,  70.417,  89.533,  73.263,  58.426,
        55.808,  64.087,  48.919,  83.119,  49.607,  71.038,  51.48 ,
        50.817,  92.925,  49.896,  72.97 ,  49.799, 107.099,  74.303,
        58.603,  72.239,  99.008,  44.572,  56.772,  43.124,  79.465,
        89.715,  75.553,  69.377,  77.15 ,  75.593,  62.811,  53.972,
        44.816, 113.329,  99.491,  39.618,  65.251, 115.72 ,  46.904,
        47.173,  69.883,  49.213,  81.503,  74.333,  59.948, 104.566,
        52.83 ,  46.36 , 106.764,  54.514,  55.612,  53.033,  71.421,
        79.564,  61.821, 110.428,  64.507,  41.443,  84.118,  88.689,
        70.206,  45.9  ,  91.686,  57.209,  77.22 ,  67.876,  77.655,
        41.076,  69.526,  77.686,  80.947,  92.598,  49.135,  71.455,
        66.116,  86.582,  62.003, 122.519,  72.379,  39.073,  73.912,
        77.953,  89.846,  80.617,  67.118,  47.686,  46.19 , 102.228,
        59.833,  50.374,  59.681,  63.838,  74.431, 131.227,  38.836,
       118.828,  98.961,  52.095,  59.464,  43.534,  63.584,  42.25 ,
        67.836,  47.634,  85.111,  55.023,  85.038,  78.043,  35.759,
        53.599,  44.901,  59.455,  90.652,  58.432,  74.721,  75.768,
        53.541,  80.877,  49.178,  53.882,  47.962,  50.703,  42.119,
        68.835, 100.511,  74.012,  65.725,  67.765,  46.432,  56.992,
        48.594,  61.75 ,  58.93 ,  45.334,  68.514,  46.199, 119.564,
        46.702, 125.882,  59.446,  74.636,  42.664,  83.298,  69.81 ,
        44.907,  45.845,  60.221, 108.412,  44.689,  67.369,  76.431,
        56.745,  82.555, 101.448,  30.168,  89.004,  59.331,  50.533,
        53.85 ,  49.603,  63.633,  59.933, 105.347,  56.164,  49.859,
        83.655,  45.408,  87.272,  45.547,  56.121,  56.107,  54.472,
        62.533,  54.487, 102.368,  72.197,  78.623,  62.601, 107.8  ,
       119.151, 111.489,  59.61 ,  35.388,  65.08 ,  61.41 ,  54.049,
        68.986,  74.319, 122.422,  79.098,  44.706,  71.479,  59.383,
        62.022,  59.629,  77.574,  50.484,  50.976,  74.066,  37.463,
        55.655,  74.701,  63.766,  94.109,  40.489,  64.926])

In [29]:
from sklearn.metrics import r2_score
r2_score(pred, y_test)

0.933684246370055